services:
  warehouse-dashboard:
    build: .
    container_name: warehouse-dashboard
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "80:5000"
    volumes:
      - ./instance:/app/instance
